### ISSUE TITLE
Redmine Thumbnail Generation does not work with the Plugin

### ISSUE THREAD

**Issue by return1** [ka8725/redmine_s3#12]
The built-in Redmine Thumbnail Generation does not work with the Plugin, when accessing the thumbnail URL redmine_S3 always redirects to the original file on S3.

**Comment by redcloak** [comment]
>UncleGene commented on Jul 8, 2014
>The only reasonable way to fix (IMHO) is to except this action, and make thumbnail logic work with s3 url.

Did this in my [fork](https://github.com/redcloak/redmine_s3). [Pull request](https://github.com/ka8725/redmine_s3/pull/32).

**Comment by return1** [comment]
was merged with #32 , thanks!
