### ISSUE TITLE
Upload big files

### ISSUE THREAD

**Issue by yfer** [ka8725/redmine_s3#18]
Until using redmine_s3 i had a redmine setup allowing me to upload big files (300Mb and sometimes even more). 
When using redmine_s3 those files upload crushes with error due to requirements of S3 cloud storage to upload such files by chunks. (i am using not Amazon s3 but API-compatible solution).

I am expirienced programmer myself, but new to ruby and rails thing , so to write this feature into plugin i need some guidance.

Could you please confirm that redmine_s3 is not capable of uploading big files(i am still not sure about this, maybe it is mine stack setup that give me the problem)
And if this problem is confirmed, than give me some kind of roadmap of how this feature best to be implemented.

Thanks.
ps: my stack for redmine is nginx+thin, both properly configurated and tested to upload such big files with pure ruby&rails(not redmine, but some test app)

**Comment by ka8725** [comment]
This [commit](https://github.com/ka8725/redmine_s3/commit/5751e94108c54d9583d0994a02cb111bea35fd75) should fix the issue.
