### ISSUE TITLE
ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task'

### ISSUE THREAD

**Issue by felipefrancisco** [ka8725/redmine_s3#34]
I'm stuck on this. Is this plugin obsolete?

    bitnami@dev:/opt/bitnami/apps/redmine/plugins/redmine_s3$ rake redmine_s3:files_to_s3 --trace
    rake aborted!
    ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task' (available in RDoc 2.4.2+) instead.
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/rdoctask.rb:1:in `<top (required)>'
    /opt/bitnami/ruby/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /opt/bitnami/ruby/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/redmine_plugin_support-0.0.5/lib/redmine_plugin_support/rdoc_task.rb:1:in `<top (required)>'
    /opt/bitnami/ruby/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /opt/bitnami/ruby/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/redmine_plugin_support-0.0.5/lib/redmine_plugin_support.rb:49:in `block in setup'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/redmine_plugin_support-0.0.5/lib/redmine_plugin_support.rb:43:in `each'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/redmine_plugin_support-0.0.5/lib/redmine_plugin_support.rb:43:in `setup'
    /opt/bitnami/apps/redmine/plugins/redmine_s3/Rakefile:6:in `<top (required)>'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
    /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
    /opt/bitnami/ruby/bin/rake:23:in `load'
    /opt/bitnami/ruby/bin/rake:23:in `<main>'
    bitnami@dev:/opt/bitnami/apps/redmine/plugins/redmine_s3$

**Comment by ka8725** [comment]
Hi, @felipefrancisco. Seems that you are first which uses Ruby 2.0 :smile: Actually it should work with the following fix: remove the `:rdoc` from this [array](https://github.com/ka8725/redmine_s3/blob/f166def62b9a2d112722325446a0dba0d8e72972/Rakefile#L9).

Please, write here about the result. You can make pull request if it works. Thanks!

**Comment by felipefrancisco** [comment]
Nice! I removed the `:doc` and i was able to continue the process. Now I'm stucked with this:


    rake aborted!
    uninitialized constant Redmine
    /opt/bitnami/apps/redmine/plugins/redmine_s3/lib/tasks/files_to_s3.rake:46:in `block (2 levels) in <top (required)>'

Unfortunatelly, I'm not a Ruby developer... what would cause the Redmine constant to be uninitialized?

**Comment by felipefrancisco** [comment]
I've replaced the `Redmine` call in [files_to_s3.rb](https://github.com/felipefrancisco/redmine_s3/blob/master/lib/tasks/files_to_s3.rake#L46) with a hardcoded string of my attachment storage path to see if the rake call would succeed. Unfortunatelly, the `Attachment` throwed the same error as `Redmine` in [line 7](https://github.com/felipefrancisco/redmine_s3/blob/master/lib/tasks/files_to_s3.rake#L7).

How are those constants supposed to be available inside this task?

**Comment by ka8725** [comment]
This exception means that `Redmine` class is not loaded (`require 'redmine'` should do the trick). But if it's not loaded automatically (Rails should do it, and Redmine based on Rails) it may be because of several reasons:

1. Incorrect installation `plugin` path
2. Incompatible version of `Redmine` or you are installing the plugin into not a `Redmine` application at all
