### ISSUE TITLE
MD5 hash doesn't reflect file contents

### ISSUE THREAD

**Issue by lotrdev** [ka8725/redmine_s3#37]
The creation of an MD5 hash within [put_to_s3](https://github.com/ka8725/redmine_s3/blob/master/lib/redmine_s3/attachment_patch.rb#L21) returns the same result every time it's run.
28: `md5 = Digest::MD5.new`
29: `self.digest = md5.hexdigest`
The original [files_to_final_location](https://github.com/redmine/redmine/blob/3ffdc863dec492808e3f05c8bd0e0e4df44650d6/app/models/attachment.rb#L109) within Redmine reads chunks of the file and applies those chunks to the md5 variable. When a file is uploaded with no changes the md5 won't change, if it's uploaded with changes it will.

One possible solution to this is to use the same method of reading the file as is used within files_to_final_location. Starting at line 25 of attachment_patch.rb:
```ruby
logger.debug("Uploading to #{disk_filename}")
content = ''
md5 = Digest::MD5.new

if @temp_file.respond_to?(:read)
  buffer = ''
  while (buffer = @temp_file.read(8192))
    content << buffer
    md5.update(buffer)
  end
else
  content = @temp_file
  md5.update(@temp_file)
end

RedmineS3::Connection.put(disk_filename_s3, filename, content, self.content_type)
self.digest = md5.hexdigest
```

I would also suggest that a better solution would include alias_method_chain on files_to_final_location, which is what I did in my own project, would be a better one.

**Comment by ka8725** [comment]
@lotrdev I think it doesn't make sense to make here alias because the origin method does many other things additionally to calculating digest. So current [this fix](https://github.com/ka8725/redmine_s3/pull/38/files) will work. What do you think?

**Comment by lotrdev** [comment]
Actually yeah that makes way more sense.

**Comment by lotrdev** [comment]
As far as the aliasing goes, it does take a bit of refactoring to work properly, however, in our setup which has multiple other plugins that have to interact properly together I found the aliasing to be a nice solution. Either way works though.

**Comment by ka8725** [comment]
https://github.com/ka8725/redmine_s3/pull/38
