### ISSUE TITLE
AWS Signature Version 2 Deprecation for Amazon S3 

### ISSUE THREAD

**Issue by ando-masaki** [ka8725/redmine_s3#42]
See:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-sig2-deprecation

**Comment by ando-masaki** [comment]
@ka8725 , how to solve this problem?

**Comment by ka8725** [comment]
I think there should be done this:
- update gem [aws-sdk](https://github.com/aws/aws-sdk-ruby)
- fix related code (probably [here](https://github.com/ka8725/redmine_s3/blob/master/lib/redmine_s3/connection.rb) and other places)

**Comment by ando-masaki** [comment]
Thanks!
